from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
import sys
import os

# =====================================================================
# 🎓 Educational Lesson: Creating a REST API Bridge
# =====================================================================
# FastAPI receives HTTP requests from the browser, runs Python code in
# the background, and returns raw data (usually JSON).
# CORS (Cross-Origin Resource Sharing) middleware is a critical security
# mechanism. By default, web browsers block pages running on port 8000
# from requesting data from port 5000. By adding CORSMiddleware and
# enabling "allow_origins=['*']", we permit our local frontend dashboard
# to securely fetch data from our backend.
# =====================================================================

# Inject workspace root into path
ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if ROOT_DIR not in sys.path:
    sys.path.append(ROOT_DIR)

# Inject skill's scripts directory so we can import local_tools directly!
SKILL_SCRIPTS_DIR = os.path.join(ROOT_DIR, ".agent", "skills", "goal-tracker", "scripts")
if SKILL_SCRIPTS_DIR not in sys.path:
    sys.path.append(SKILL_SCRIPTS_DIR)

import local_tools as tools
from backend.app.database import init_db

app = FastAPI(title="goalmanager REST API")

# Configure CORS Middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Permits all local dashboard connections
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.middleware("http")
async def add_no_cache_header(request, call_next):
    """Disable browser caching of static files (index.html, styles.css, app.js)."""
    response = await call_next(request)
    response.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "0"
    return response


@app.on_event("startup")
def on_startup():
    """Ensure database file and schemas exist on startup."""
    init_db()


@app.get("/api/dashboard")
def get_dashboard():
    """
    Exposes a clean REST API endpoint.
    Returns the parsed, nested goals tree and priority-sorted tasks.
    """
    import json
    # Simply load the serialized string state generated by our local_tools
    state_str = tools.get_dashboard_state()
    return json.loads(state_str)


# Mount the frontend directory to serve static assets (index.html, styles.css, app.js)
app.mount("/", StaticFiles(directory=os.path.join(ROOT_DIR, "frontend"), html=True), name="frontend")


if __name__ == "__main__":
    import uvicorn
    print("Starting local dev server at http://127.0.0.1:8000")
    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=True)
